spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.show-sql=true

spring.jpa.properties.jakarta.persistence.validation.mode=auto

app.jwt.secret=s+C4VzR1+U2A/hN7Z4q6lW9a8fQ3cM2pI7bB5aY0gXz8jQ4eF2iL1uS7rT3wP6b
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000