services:
  db:
    build: ./db
    container_name: gxssvp-postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - gxssvp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: gxssvp-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gxssvp-network

  frontend:
    build: ./frontend
    container_name: gxssvp-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - gxssvp-network

volumes:
  postgres_data:

networks:
  gxssvp-network:
    driver: bridge